name = "testProject"
uuid = "c4e7b264-438b-4e89-84e3-605eddae9385"
authors = ["Jerell James <jerell1998@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
